open Kernel.Info
open Fix.Indexing
open Utils
open Misc

let (.?()) = Boolvector.test

(* The logic:
   - Tree-sitter do not expect an explicit "EOF" symbol, we strip them from the
     original grammar
   - Rules involving `error` symbol are likely noise too, we ignore them
   - Tree-sitter do not support ϵ-rules -> rewrite grammar
   - Conflicts are specified with a slightly different formalism ->
     reverse-engineer conflict resolution from the generated automaton

   The flow:
   - analyze the grammar:
     - find which productions to import
     - find which derive non-null string (for rewriting of ϵ-rules and nts)
   - from the analysis, we can directly generate a tree-sitter template
   - but we don't stop here:
     - transform the conflicts in the automaton into a set of
       constraints
     - solve the constraints
     - inject the solution in the grammar prior to generation

   Constraints are solved as follow:
   - tree-sitter sets a precedence value at the level of productions
   - for each item, we will generate a variable representing its precedence level
   - the equations are all of the form `var ≥_{Left,Right,Prec} var`, so we can
     compute the SCC of the graph generated by these relations to rank them
   - however doing this naively introduce too many precedence levels and do not
     support associativity out of the box
   - if all rules involved in a cycle are ... TODO
*)

(* Pre-compute some properties of the grammar *)
type 'g analysis = {
  g: 'g grammar;
  (* Productions to consider *)
  valid_prod: 'g production Boolvector.t;
  (* Non-terminals deriving a non-empty string *)
  nonnull_nt: 'g nonterminal Boolvector.t;
  (* Productions deriving a non-empty string *)
  nonnull_prod: 'g production Boolvector.t;
}

let analyze g =
  (* A production is valid if it has no `error` symbol *)
  let valid_prod = Boolvector.init (Production.cardinal g) begin fun prod ->
      Array.for_all (fun sym ->
          match Symbol.desc g sym with
          | T t -> Terminal.kind g t <> `ERROR
          | _ -> true
        ) (Production.rhs g prod)
    end
  in
  (* Pre-compute productions in which a non-terminal occurs *)
  let nt_occurrences = Vector.make (Nonterminal.cardinal g) IndexSet.empty in
  Index.rev_iter (Production.cardinal g) begin fun prod ->
    if valid_prod.?(prod) then
      Array.iter begin fun sym ->
        match Symbol.desc g sym with
        | T _ -> ()
        | N nt -> nt_occurrences.@(nt) <- IndexSet.add prod
      end (Production.rhs g prod)
  end;
  (* Determine nt and prod that can derive a non-empty string *)
  let nonnull_nt = Boolvector.make (Nonterminal.cardinal g) false in
  let nonnull_prod = Boolvector.make (Production.cardinal g) false in
  let rec set_prod prod =
    if not nonnull_prod.?(prod) then (
      Boolvector.set nonnull_prod prod;
      set_nt (Production.lhs g prod)
    )
  and set_nt nt =
    if not nonnull_nt.?(nt) then (
      Boolvector.set nonnull_nt nt;
      IndexSet.iter set_prod nt_occurrences.:(nt)
    )
  in
  Index.iter (Production.cardinal g) begin fun prod ->
    if
      Array.exists (fun sym ->
        match Symbol.desc g sym with
        | N _ -> false
        | T t -> match Terminal.kind g t with
          | `REGULAR -> true
          | `EOF -> false
          | `ERROR | `PSEUDO -> false
      ) (Production.rhs g prod)
    then set_prod prod
  end;
  {g; valid_prod; nonnull_nt; nonnull_prod}

(* Documents for constructing indented output *)
module Doc = struct
  type document =
    | Text of string
    | Indent of (int * document)
    | Join of document * document

  let empty = Text ""

  let text x = Text x

  let join x y =
    match x, y with
    | Text "", v | v, Text "" -> v
    | _ -> Join (x, y)

  let list = function
    | [] -> empty
    | [x] -> x
    | x :: xs -> List.fold_left join x xs

  let list_map f docs = list (List.map f docs)

  let indent n = function
    | Text "" -> Text ""
    | Indent (m, doc) -> Indent (n + m, doc)
    | doc -> Indent (n, doc)

  let wrap a b c = join a (join c b)

  let rec concat sep f ?(first=f) = function
    | [] -> empty
    | [x] -> first x
    | x :: xs -> join (first x) (join sep (concat sep f xs))

  let padding = String.make 80 ' '

  let rec render_text nl o n pos text =
    match String.index_from_opt text pos '\n' with
    | None ->
      let len = String.length text - pos in
      if len > 0 then (
        if !nl then (
          o padding 0 (Int.min 80 n);
          nl := false;
        );
        o text pos len
      );
    | Some pos' ->
      if pos' > pos && !nl then (
        o padding 0 (Int.min 80 n);
        nl := false;
      );
      let pos' = pos' + 1 in
      o text pos (pos' - pos);
      nl := true;
      render_text nl o n pos' text

  let rec render nl o n = function
    | Text text -> render_text nl o n 0 text
    | Indent (d, doc) -> render nl o (n + d) doc
    | Join (a, b) ->
      render nl o n a;
      render nl o n b

  let render o n doc = render (ref false) o n doc
end


(* How do we represent conflicts?

   If some state present a conflict, we start by building a map of preserved
   actions by lookahead symbol.
*)


module Conflict = struct

  type 'g actions = {
    shift: 'g item indexset;
    reduce: 'g item indexset;
  }

  let get_actions map t =
    match IndexMap.find_opt t map with
    | Some a -> a
    | None -> {shift = IndexSet.empty; reduce = IndexSet.empty}

  let add_shift g tr map =
    match Symbol.desc g (Transition.symbol g tr) with
    | N _ -> map
    | T term ->
      let items = Lr1.items g (Transition.target g tr) in
      IndexSet.iter (fun item -> assert (Item.position g item > 0)) items;
      let actions = get_actions map term in
      assert (IndexSet.is_empty actions.shift);
      IndexMap.add term {actions with shift = items} map

  let add_reduction g red map =
    let prod = Reduction.production g red in
    let item = Item.make g prod (Production.length g prod) in
    IndexSet.fold begin fun term map ->
      let actions = get_actions map term in
      let reduce = IndexSet.add item actions.reduce in
      IndexMap.add term {actions with reduce = reduce} map
    end (Reduction.lookaheads g red) map

  let remove_reduce g map (term, prod) =
    let actions = get_actions map term in
    let item = Item.make g prod (Production.length g prod) in
    let reduce = IndexSet.remove item actions.reduce in
    assert (reduce != actions.reduce);
    IndexMap.add term {actions with reduce} map

  type relation =
    | Shift_over_reduce
    | Reduce_over_shift
    | Reduce_reduce

  type 'g edge = {
    source: 'g item index;
    target: 'g item index;
    relation: relation;
  }

  let register_removed_shift g map register (term, lr1) =
    let actions = get_actions map term in
    assert (IndexSet.is_empty actions.shift);
    IndexSet.iter begin fun source ->
      IndexSet.iter begin fun target ->
        register {source; target; relation = Reduce_over_shift}
      end actions.reduce
    end (Lr1.items g lr1)

  let register_removed_reduce g map register (term, prods) =
    let actions = get_actions map term in
    List.iter begin fun prod ->
      let source = Item.make g prod (Production.length g prod) in
      IndexSet.iter begin fun target ->
        register {source; target; relation = Shift_over_reduce}
      end actions.shift;
      IndexSet.iter begin fun target ->
        register {source; target; relation = Reduce_reduce}
      end actions.reduce
    end prods

  let process_lr1 g register lr1 =
    match
      Conflicts.silent_transition_conflicts g lr1,
      Conflicts.silent_reduction_conflicts g lr1
    with
    | [], [] -> ()
    | removed_shift, removed_reduce ->
      let actions =
        IndexMap.empty
        |> IndexSet.fold (add_shift g) (Transition.successors g lr1)
        |> IndexSet.fold (add_reduction g) (Reduction.from_lr1 g lr1)
      in
      (* Remove extra ones *)
      let actions =
        List.fold_left (remove_reduce g)
          actions (Conflicts.extra_reductions g lr1)
      in
      (* Register conflicts *)
      List.iter
        (register_removed_shift g actions register)
        removed_shift;
      List.iter
        (register_removed_reduce g actions register)
        removed_reduce

  module UF : sig
    type 'n t
    val make : 'n cardinal -> 'n t
    val find : 'n t -> 'n index -> 'n index
    val union : 'n t -> 'n index -> 'n index -> unit
  end = struct
    type 'n t = ('n, 'n index) vector
    let make n = Vector.init n Fun.id

    let rec find t i =
      let i' = t.:(i) in
      if i != i' then
        let i'' = find t i' in
        if i'' != i' then
          t.:(i) <- i'';
        i''
      else
        i'

    let union t i j =
      let i = find t i and j = find t j in
      if i < j then
        t.:(j) <- i
      else if j < i then
        t.:(i) <- j
  end

  type associativity =
    | Left
    | Right
    | Prec
    | Invalid

  let solve (type g) (g : g grammar) =
    (* Collect all conflicts by item *)
    let successors = Vector.make (Item.cardinal g) [] in
    let predecessors = Vector.make (Item.cardinal g) [] in
    let register edge =
      successors.@(edge.source) <- List.cons edge;
      predecessors.@(edge.target) <- List.cons edge
    in
    Index.iter (Lr1.cardinal g) (process_lr1 g register);
    (* Generate SCC of the graph induced by conflicts *)
    let (module SCC) =
      Tarjan.indexed_scc (Item.cardinal g)
        ~succ:(fun f i -> List.iter (fun edge -> f edge.target) successors.:(i))
    in
    (* There should be no cycles at this point, otherwise we have an untranslatable conflict.
       ... Actually, there can be cycles because both a shift [A → α a .] and a
       reduce [A → a α] are represented by the same item.
       assert (Vector.for_all IndexSet.is_singleton SCC.nodes); *)
    (* This could be sufficient, but the solution produced would be naive and
       inelegant.  We will try to merge items of the same production to give
       them a single precedence level:
       - identify relation between items: SR (Shift/Reduce), RS (Reduce/Shift)
         and RR (Reduce/Reduce) sets.
       - from these sets, we can deduce the directly unmergeable items.
       - this is a conflict graph, that we can use to color items
       - from the coloring we get a global view of mergeable items *)
    let scc_sr = Vector.make SCC.n IndexSet.empty in
    let scc_rs = Vector.make SCC.n IndexSet.empty in
    let scc_rr = Vector.make SCC.n IndexSet.empty in
    Vector.iteri begin fun scc nodes ->
      let sr = ref IndexSet.empty in
      let rs = ref IndexSet.empty in
      let rr = ref IndexSet.empty in
      let self_sr = ref false in
      let self_rs = ref false in
      let self_rr = ref false in
      IndexSet.iter begin fun node ->
        List.iter begin fun edge ->
          let scc' = SCC.component.:(edge.source) in
          if Index.equal scc scc' then (
            match edge.relation with
            | Shift_over_reduce -> self_sr := true
            | Reduce_over_shift -> self_rs := true
            | Reduce_reduce     -> self_rr := true
          ) else (
            let inherited =
              IndexSet.union
                (IndexSet.union scc_sr.:(scc') scc_rs.:(scc'))
                (IndexSet.add scc' scc_rr.:(scc'))
            in
            match edge.relation with
            | Shift_over_reduce ->
              sr := IndexSet.union !sr inherited
            | Reduce_over_shift ->
              rs := IndexSet.union !rs inherited
            | Reduce_reduce     ->
              rr := IndexSet.union !rr inherited
          )
        end predecessors.:(node)
      end nodes;
      let union () = IndexSet.add scc (IndexSet.union !sr (IndexSet.union !rs !rr)) in
      begin match !self_sr, !self_rs, !self_rr with
        | false, false, false -> ()
        | true , false, false -> sr := union ()
        | false, true , false -> rs := union ()
        | _ -> invalid_arg "cyclic precedences"
      end;
      scc_sr.:(scc) <- !sr;
      scc_rs.:(scc) <- !rs;
      scc_rr.:(scc) <- !rr;
    end SCC.nodes;

    (* (\* Generate conflict graphs *\) *)
    (* let conflicts = Vector.init SCC.n begin fun scc -> *)
    (*     (\* What is incompatible ? *)
    (*        -> sccs that are reachable via rr *)
    (*        -> sccs that are reachable via sr and rs *\) *)
    (*     IndexSet.fused_inter_union ~acc:scc_rr.:(scc) scc_sr.:(scc) scc_rs.:(scc) *)
    (*   end *)
    (* in *)
    (* (\* Make the graph undirected *\) *)
    (* begin *)
    (*   let conflicts' = Vector.make SCC.n IndexSet.empty in *)
    (*   Vector.rev_iteri begin fun scc sccs -> *)
    (*     IndexSet.iter (fun scc' -> conflicts'.@(scc') <- IndexSet.add scc) sccs *)
    (*   end conflicts; *)
    (*   Vector.iteri begin fun scc sccs' -> *)
    (*     conflicts.@(scc) <- IndexSet.union sccs' *)
    (*   end conflicts'; *)
    (* end; *)
    (* (\* Sanity check: no loops *\) *)
    (* Vector.iteri (fun scc sccs -> assert (not (IndexSet.mem scc sccs))) conflicts; *)
    (* (\* Coloration *\) *)
    (* let colors = Vector.make SCC.n (-1) in *)
    (* (\* Process sccs with more constraints first; Welsh-Powell heuristic *\) *)
    (* let arr = Vector.as_array (Vector.mapi (fun scc sccs -> (scc, IndexSet.cardinal sccs, sccs)) conflicts) in *)
    (* Array.sort (fun (_,c1,_) (_,c2,_) -> Int.compare c2 c1) arr; *)
    (* Array.iter begin fun (scc,count,sccs) -> *)
    (*   if count > 0 then begin *)
    (*     let check_color c = IndexSet.for_all (fun scc' -> colors.:(scc') <> c) sccs in *)
    (*     let c = ref 0 in *)
    (*     while not (check_color !c) do incr c done; *)
    (*     colors.:(scc) <- !c; *)
    (*   end *)
    (* end arr; *)
    (* (\* Now we are ready to merge items :) *\) *)
    (* let uf = UF.make (Item.cardinal g) in *)
    (* Index.iter (Production.cardinal g) begin fun prod -> *)
    (*   let color = ref (-1) in *)
    (*   for i = 1 to Production.length g prod do *)
    (*     let item = Item.make g prod i in *)
    (*     if not (List.is_empty successors.:(item) && List.is_empty predecessors.:(item)) then begin *)
    (*       let scc = SCC.component.:(item) in *)
    (*       let color' = colors.:(scc) in *)
    (*       if color' = -1 *)
    (*       then colors.:(scc) <- !color *)
    (*       else color := color' *)
    (*     end *)
    (*   done; *)
    (*   color := (-1); *)
    (*   let ritem = ref None in *)
    (*   for i = 1 to Production.length g prod do *)
    (*     let item = Item.make g prod i in *)
    (*     if not (List.is_empty successors.:(item) && List.is_empty predecessors.:(item)) then begin *)
    (*       let scc = SCC.component.:(item) in *)
    (*       let color' = colors.:(scc) in *)
    (*       if color' = !color then begin *)
    (*         match !ritem with *)
    (*         | None -> () *)
    (*         | Some item' -> UF.union uf item item' *)
    (*       end; *)
    (*       color := color'; *)
    (*       ritem := Some item; *)
    (*     end *)
    (*   done *)
    (* end; *)
    (* (\* Ok, the union-find gives merged items... *\) *)
    (* (\* Compute a last SCC before attributing ranks *\) *)
    (* let successors2 = Vector.make (Item.cardinal g) [] in *)
    (* Vector.iteri begin fun item successors -> *)
    (*   let item' = UF.find uf item in *)
    (*   successors2.@(item') <- List.cons successors *)
    (* end successors; *)
    (* let (module SCC2) = Tarjan.indexed_scc (Item.cardinal g) *)
    (*     ~succ:(fun f i -> List.iter (List.iter (fun edge -> f edge.target)) successors2.:(i)) *)
    (* in *)
    (* (\* Now we have all that is needed to compute ranks *\) *)
    (* let ranks = Vector.make SCC2.n 0 in *)
    (* let assocs = *)
    (*   (\* For each SCC, compute the rank based on predecessors (and built-in nodes) *\) *)
    (*   Vector.mapi begin fun scc nodes -> *)
    (*     let level = ref (-1) in *)
    (*     let self_sr = ref false in *)
    (*     let self_rs = ref false in *)
    (*     let self_rr = ref false in *)
    (*     IndexSet.iter begin fun node -> *)
    (*       List.iter begin fun edge -> *)
    (*         let scc' = SCC2.component.:(edge.source) in *)
    (*         if Index.equal scc scc' then ( *)
    (*           match edge.relation with *)
    (*           | Shift_over_reduce -> self_sr := true *)
    (*           | Reduce_over_shift -> self_rs := true *)
    (*           | Reduce_reduce     -> self_rr := true *)
    (*         ) else *)
    (*           level := Int.max !level ranks.:(scc') *)
    (*       end predecessors.:(node) *)
    (*     end nodes; *)
    (*     let assoc = match !self_sr, !self_rs, !self_rr with *)
    (*       | false, false, false -> Prec *)
    (*       | true , false, false -> Right *)
    (*       | false, true , false -> Left *)
    (*       | _ -> *)
    (*         Printf.eprintf "self_sr:%b self_rs:%b self_rr:%b\n" *)
    (*           !self_sr !self_rs !self_rr; *)
    (*         Invalid *)
    (*     in *)
    (*     ranks.:(scc) <- (!level + 1); *)
    (*     assoc *)
    (*   end SCC2.nodes *)
    (* in *)
    (* let it_ranks = Vector.make (Item.cardinal g) (-1) in *)
    (* let it_assoc = Vector.make (Item.cardinal g) Prec in *)
    (* Vector.iteri begin fun scc nodes -> *)
    (*   let rank = ranks.:(scc) and assoc = assocs.:(scc) in *)
    (*   IndexSet.iter begin fun node -> *)
    (*     it_ranks.:(node) <- rank; *)
    (*     it_assoc.:(node) <- assoc; *)
    (*   end nodes *)
    (* end SCC2.nodes; *)
    (* Index.iter (Production.cardinal g) begin fun prod -> *)
    (*   let rank = ref (-1) in *)
    (*   let assoc = ref Prec in *)
    (*   for i = Production.length g prod - 1 downto 1 do *)
    (*     let item = Item.make g prod i in *)
    (*     if it_ranks.:(item) = -1 then ( *)
    (*       it_ranks.:(item) <- !rank; *)
    (*       it_assoc.:(item) <- !assoc; *)
    (*     ) else ( *)
    (*       rank := it_ranks.:(item); *)
    (*       assoc := it_assoc.:(item); *)
    (*     ) *)
    (*   done *)
    (* end; *)
    (* (it_ranks, it_assoc) *)
end

module Converter = struct
  let (!!) = Doc.text
  let (^^) = Doc.join

  let bind_rule lhs rhs =
    !!lhs ^^ !!": $ => " ^^ rhs ^^ !!",\n"

  let mangled g nt =
    Symbol.to_string ~mangled:true g (Symbol.inj_n g nt)

  let import_terminal g term =
    match Terminal.kind g term with
    | `EOF -> "token(\"EOF\")"
    | _ ->
      let rhs = Option.value (Terminal.alias g term)
          ~default:(Terminal.to_string g term)
      in
      if rhs = "" || rhs.[0] <> '"'
      then Printf.sprintf "token(%S)" rhs
      else Printf.sprintf "token(%s)" rhs

  let import_raw_producer g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N nt -> !!"$." ^^ !!(mangled g nt)

  let import_producer not_optional g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N n ->
      let doc = !!"$." ^^ !!(mangled g n) in
      if Nonterminal.nullable g n && not not_optional
      then Doc.wrap !!"optional(" !!")" doc
      else doc

  let symbol_nonnull ga sym =
    match Symbol.desc ga.g sym with
    | T t -> Terminal.kind ga.g t = `REGULAR
    | N n -> ga.nonnull_nt.?(n)

  let symbol_nullable g sym =
    match Symbol.desc g sym with
    | T _ -> false
    | N n -> Nonterminal.nullable g n

  let import_production ga ranks assocs prod =
    assert ga.nonnull_prod.?(prod);
    let rhs = (Production.rhs ga.g prod) in
    let not_optional = ref (Array.for_all (symbol_nullable ga.g) rhs) in
    let tail = ref [] in
    let last_rank = ref (-1, Conflict.Invalid) in
    let flush_tail () =
      match !tail with
      | [] -> !!"seq()"
      | [x] -> x
      | xs -> Doc.wrap !!"seq(" !!")" (Doc.concat !!"," Fun.id xs)
    in
    let flush_rank () =
      match !tail, !last_rank with
      | [], _ | _, (-1, _) -> ()
      | _ ->
        let level, assoc = !last_rank in
        let assoc = match assoc with
          | Left -> "prec.left"
          | Right -> "prec.right"
          | Invalid -> "prec.invalid"
          | Prec-> "prec"
        in
        tail := [Doc.wrap !!(Printf.sprintf "%s(%d," assoc level) !!")" (flush_tail ())]
    in
    let add_sym rank sym =
      if symbol_nonnull ga sym then (
        if rank <> !last_rank then flush_rank ();
        tail := import_producer !not_optional ga.g sym :: !tail;
        not_optional := false
      );
      last_rank := rank
      (* Logic:
         - if sym is not non_null, skip
         - if (rank, assoc) <> last_rank, tail <> [] then flush_rank ()
         - last_rank := rank, assoc
         - if nullable && !optional
           then tail = option(sym) :: tail
           else tail = sym :: tail
         - optional := false
      *)
    in
    for pos = Array.length rhs - 1 downto 0 do
      let item = Item.make ga.g prod (pos + 1) in
      add_sym (ranks.:(item), assocs.:(item)) rhs.(pos)
    done;
    flush_rank ();
    flush_tail ()

  let import_nonterminals ga ranks assocs =
    (* Pre-compute productions defining a non-terminal *)
    let nt_prods = Vector.make (Nonterminal.cardinal ga.g) IndexSet.empty in
    let entrypoint = ref None in
    Index.rev_iter (Production.cardinal ga.g) begin fun prod ->
      if ga.valid_prod.?(prod) && ga.nonnull_prod.?(prod) then
        match Production.kind ga.g prod with
        | `REGULAR ->
          nt_prods.@(Production.lhs ga.g prod) <- IndexSet.add prod
        | `START ->
          if Option.is_none !entrypoint then
            let n = match Symbol.desc ga.g (Production.rhs ga.g prod).(0) with
              | Symbol.T _ -> assert false
              | Symbol.N n -> n
            in
            entrypoint := Some n
    end;
    let rules =
      (* Output all productions of a non-terminal *)
      Vector.to_seqi nt_prods |>
      Seq.filter_map begin fun (nt, prods) ->
        if IndexSet.is_empty prods then None else Some begin
            let rhs =
              if IndexSet.is_singleton prods then
                import_production ga ranks assocs (IndexSet.choose prods)

              else
                Doc.wrap !!"choice(\n" !!"\n)"
                  (Doc.indent 2 (Doc.concat !!",\n"
                                   (import_production ga ranks assocs)
                                   (IndexSet.elements prods)))
            in
            (nt, rhs)
          end
      end
    in
    (Option.get !entrypoint, rules)

  let convert_syntax ga ranks assocs basename =
    let entrypoint, rules = import_nonterminals ga ranks assocs in
    (*let entrypoint =
      if List.exists (fun (nt, _) -> mangled ga.g nt = "start") rules then
        "start"
      else
        List.find_map (fun (nt, _) ->
            if Nonterminal.kind ga.g nt = `START
            then Some (mangled ga.g nt)
            else None
          ) rules
        |> Option.get
      in*)
    Doc.list [
      !!"export default {\n";
      Doc.indent 2 @@ Doc.list [
        !!"name: '"; !!basename; !!"',\n";
        !!"rules: {\n";
        Doc.indent 2 @@ Doc.list [
          bind_rule "start" !!("$." ^ mangled ga.g entrypoint);
          Doc.list_map
            (fun (lhs, rhs) -> bind_rule (mangled ga.g lhs) rhs)
            (List.of_seq rules);
          (*Doc.list (List.filter_map import_token symbols);*)
        ];
        !!"}\n";
      ];
      !! "};\n";
    ]
end

let import g basename =
  let ga = analyze g in
  let ranks, assocs = Conflict.solve g in
  let doc = Converter.convert_syntax ga ranks assocs basename in
  Doc.render (output_substring stdout) 0 doc
