open Kernel.Info
open Fix.Indexing
open Utils
open Misc

let (.?()) = Boolvector.test

(* The logic:
   - Tree-sitter do not expect an explicit "EOF" symbol, we strip them from the
     original grammar
   - Rules involving `error` symbol are likely noise too, we ignore them
   - Tree-sitter do not support ϵ-rules -> rewrite grammar
   - Conflicts are specified with a slightly different formalism ->
     reverse-engineer conflict resolution from the generated automaton

   The flow:
   - analyze the grammar:
     - find which productions to import
     - find which derive non-null string (for rewriting of ϵ-rules and nts)
   - from the analysis, we can directly generate a tree-sitter template
   - but we don't stop here:
     - transform the conflicts in the automaton into a set of
       constraints
     - solve the constraints
     - inject the solution in the grammar prior to generation

   Constraints are solved as follow:
   - tree-sitter sets a precedence value at the level of productions
   - for each item, we will generate a variable representing its precedence level
   - the equations are all of the form `var ≥_{Left,Right,Prec} var`, so we can
     compute the SCC of the graph generated by these relations to rank them
   - however doing this naively introduce too many precedence levels and do not
     support associativity out of the box
   - if all rules involved in a cycle are ... TODO
*)

(* Pre-compute some properties of the grammar *)
type 'g analysis = {
  g: 'g grammar;
  (* Productions to consider *)
  valid_prod: 'g production Boolvector.t;
  (* Non-terminals deriving a non-empty string *)
  nonnull_nt: 'g nonterminal Boolvector.t;
  (* Productions deriving a non-empty string *)
  nonnull_prod: 'g production Boolvector.t;
}

let analyze g =
  (* A production is valid if it has no `error` symbol *)
  let valid_prod = Boolvector.init (Production.cardinal g) begin fun prod ->
      Array.for_all (fun sym ->
          match Symbol.desc g sym with
          | T t -> Terminal.kind g t <> `ERROR
          | _ -> true
        ) (Production.rhs g prod)
    end
  in
  (* Pre-compute productions in which a non-terminal occurs *)
  let nt_occurrences = Vector.make (Nonterminal.cardinal g) IndexSet.empty in
  Index.rev_iter (Production.cardinal g) begin fun prod ->
    if valid_prod.?(prod) then
      Array.iter begin fun sym ->
        match Symbol.desc g sym with
        | T _ -> ()
        | N nt -> nt_occurrences.@(nt) <- IndexSet.add prod
      end (Production.rhs g prod)
  end;
  (* Determine nt and prod that can derive a non-empty string *)
  let nonnull_nt = Boolvector.make (Nonterminal.cardinal g) false in
  let nonnull_prod = Boolvector.make (Production.cardinal g) false in
  let rec set_prod prod =
    if not nonnull_prod.?(prod) then (
      Boolvector.set nonnull_prod prod;
      set_nt (Production.lhs g prod)
    )
  and set_nt nt =
    if not nonnull_nt.?(nt) then (
      Boolvector.set nonnull_nt nt;
      IndexSet.iter set_prod nt_occurrences.:(nt)
    )
  in
  Index.iter (Production.cardinal g) begin fun prod ->
    if
      Array.exists (fun sym ->
        match Symbol.desc g sym with
        | N _ -> false
        | T t -> match Terminal.kind g t with
          | `REGULAR -> true
          | `EOF -> false
          | `ERROR | `PSEUDO -> false
      ) (Production.rhs g prod)
    then set_prod prod
  end;
  {g; valid_prod; nonnull_nt; nonnull_prod}

(* Documents for constructing indented output *)
module Doc = struct
  type document =
    | Text of string
    | Indent of (int * document)
    | Join of document * document

  let empty = Text ""

  let text x = Text x

  let join x y =
    match x, y with
    | Text "", v | v, Text "" -> v
    | _ -> Join (x, y)

  let list = function
    | [] -> empty
    | [x] -> x
    | x :: xs -> List.fold_left join x xs

  let list_map f docs = list (List.map f docs)

  let indent n = function
    | Text "" -> Text ""
    | Indent (m, doc) -> Indent (n + m, doc)
    | doc -> Indent (n, doc)

  let wrap a b c = join a (join c b)

  let rec concat sep f ?(first=f) = function
    | [] -> empty
    | [x] -> first x
    | x :: xs -> join (first x) (join sep (concat sep f xs))

  let padding = String.make 80 ' '

  let rec render_text nl o n pos text =
    match String.index_from_opt text pos '\n' with
    | None ->
      let len = String.length text - pos in
      if len > 0 then (
        if !nl then (
          o padding 0 (Int.min 80 n);
          nl := false;
        );
        o text pos len
      );
    | Some pos' ->
      if pos' > pos && !nl then (
        o padding 0 (Int.min 80 n);
        nl := false;
      );
      let pos' = pos' + 1 in
      o text pos (pos' - pos);
      nl := true;
      render_text nl o n pos' text

  let rec render nl o n = function
    | Text text -> render_text nl o n 0 text
    | Indent (d, doc) -> render nl o (n + d) doc
    | Join (a, b) ->
      render nl o n a;
      render nl o n b

  let render o n doc = render (ref false) o n doc
end

module Merger : sig

  type ('n, 'b) _t
  type 'n t = T : ('n, 'b) _t -> 'n t

  val make : 'n cardinal -> 'n t
  val link_left : ('n, 'b) _t -> 'n index -> 'n index -> unit
  val link_right : ('n, 'b) _t -> 'n index -> 'n index -> unit
  val bridge : ('n, 'b) _t -> 'n index -> 'n index -> 'b index

  val solve : ('n, 'b) _t -> 'b Boolvector.t
end = struct

  type ('n, 'm) edges = {
    succ_l: ('n, 'm indexset) vector;
    succ_r: ('n, 'm indexset) vector;
    pred_l: ('n, 'm indexset) vector;
    pred_r: ('n, 'm indexset) vector;
  }

  type ('n, 'b) _t = {
    edges: ('n, ('n, 'b) Sum.n) edges;
    bridges: ('n, ('n, 'b) Sum.n indexset) vector;
    count: 'b cardinal;
    fresh: unit -> 'b index;
  }

  type 'n t = T : ('n, 'b) _t -> 'n t

  let make_edges (type n) (n : n cardinal) =
    let succ_l = Vector.make n IndexSet.empty in
    let succ_r = Vector.make n IndexSet.empty in
    let pred_l = Vector.make n IndexSet.empty in
    let pred_r = Vector.make n IndexSet.empty in
    {succ_l; succ_r; pred_l; pred_r}

  let make (type n) (n : n cardinal) =
    let module B = Gensym() in
    let edges = make_edges n in
    let bridges = Vector.make n IndexSet.empty in
    T {edges; bridges; count=B.n; fresh=B.fresh}

  let bridge t i1 i2 =
    let b = t.fresh () in
    let n = Vector.length t.edges.pred_l in
    t.bridges.@(i1) <- IndexSet.add (Sum.inj_r n b);
    t.bridges.@(i2) <- IndexSet.add (Sum.inj_r n b);
    b

  let link_left t i1 i2 =
    t.edges.succ_l.@(i1) <- IndexSet.add (Sum.inj_l i2);
    t.edges.pred_l.@(i2) <- IndexSet.add (Sum.inj_l i1)

  let link_right t i1 i2 =
    t.edges.succ_r.@(i1) <- IndexSet.add (Sum.inj_l i2);
    t.edges.pred_r.@(i2) <- IndexSet.add (Sum.inj_l i1)

  let link_l v i1 i2 =
    v.succ_l.@(i1) <- IndexSet.add i2;
    v.pred_l.@(i2) <- IndexSet.add i1

  let link_r v i1 i2 =
    v.succ_r.@(i1) <- IndexSet.add i2;
    v.pred_r.@(i2) <- IndexSet.add i1

  let iter' i s f =
    IndexSet.iter (fun i' -> if not (Index.equal i i') then f i) s

  (* Iterate connections node *)
  let iter_connections unregister v i =
    IndexSet.iter (unregister v.pred_l) v.succ_l.:(i);
    IndexSet.iter (unregister v.pred_r) v.succ_r.:(i);
    IndexSet.iter (unregister v.succ_l) v.pred_l.:(i);
    IndexSet.iter (unregister v.succ_r) v.pred_r.:(i)

  (* Connect predecessors to successors *)
  let eliminate unregister v bridges i =
    let pred_l = v.pred_l.:(i) and succ_l = v.succ_l.:(i) in
    let pred_r = v.pred_r.:(i) and succ_r = v.succ_r.:(i) in
    let self_l = IndexSet.mem i pred_l in
    let self_r = IndexSet.mem i pred_r in
    (* Follow left links *)
    iter' i pred_l begin fun prev_l ->
      iter' i succ_l begin fun next_l ->
        link_l v prev_l next_l;
        if self_r then
          link_r v prev_l next_l;
      end;
      IndexSet.iter begin fun bridge ->
        link_l v prev_l bridge;
        if self_r then
          link_r v prev_l bridge;
      end bridges;
    end;
    (* Follow right links *)
    iter' i pred_r begin fun prev_r ->
      iter' i succ_r begin fun next_r ->
        link_r v prev_r next_r;
        if self_l then
          link_l v prev_r next_r;
      end;
      IndexSet.iter begin fun bridge ->
        link_r v prev_r bridge;
        if self_l then
          link_l v prev_r bridge;
      end bridges;
    end;
    iter_connections unregister v i

  (* Trivial bridges:
     - strictly-l or strictly-r: doesn't contribute to LR cycles
     - 0-in-degree or 0-out-degree (Khan algorithm) *)
  let can_eliminate edges i =
    let no_pred_l = IndexSet.is_empty edges.pred_l.:(i) in
    let no_pred_r = IndexSet.is_empty edges.pred_r.:(i) in
    let no_succ_l = IndexSet.is_empty edges.succ_l.:(i) in
    let no_succ_r = IndexSet.is_empty edges.succ_r.:(i) in
    (* equiv: (no_pred_l || no_succ_r) && (no_pred_r || no_succ_l) *)
    ((no_pred_l && no_pred_r) || (no_succ_l && no_succ_r) ||
     (no_pred_l && no_succ_l) || (no_pred_r && no_succ_r)) &&
    not (no_pred_l && no_pred_r && no_succ_l && no_succ_r)

  let solve t =
      let empty = Vector.make t.count IndexSet.empty in
      let edges = {
        succ_l = Vector.concat t.edges.succ_l empty;
        succ_r = Vector.concat t.edges.succ_r empty;
        pred_l = Vector.concat t.edges.pred_l empty;
        pred_r = Vector.concat t.edges.pred_r empty;
      } in
      let n = Vector.length t.edges.pred_l in
      Index.iter n (fun i0 ->
          let i = Sum.inj_l i0 in
          let unregister_node arr j = arr.@(j) <- IndexSet.remove i in
          eliminate unregister_node edges t.bridges.:(i0) i
        );
      let burned = Boolvector.make t.count false in
      let todo = ref [] in
      let unregister_bridge i arr j =
        let s = IndexSet.remove i arr.:(j) in
        arr.:(j) <- s;
        if IndexSet.is_empty s && can_eliminate edges i then
          push todo i
      in
      let burn_bridge i =
        match Sum.prj n i with
        | L _ -> assert false
        | R b ->
          Boolvector.set burned b;
          iter_connections (unregister_bridge i) edges i
      in
      let eliminate_bridge i =
        eliminate (unregister_bridge i) edges IndexSet.empty i
      in
      let rec cleanup () =
        match !todo with
        | [] -> ()
        | todo' ->
          todo := [];
          List.iter eliminate_bridge todo';
          cleanup ()
      in
      Index.iter t.count (fun b ->
          let i = Sum.inj_r n b in
          if can_eliminate edges i then
            eliminate_bridge i
        );
      cleanup ();
      (* Collect remaining bridges *)
      let remaining = ref [] in
      Index.iter t.count (fun b ->
          let i = Sum.inj_r n b in
          if IndexSet.is_not_empty edges.pred_l.:(i) ||
             IndexSet.is_not_empty edges.pred_r.:(i) ||
             IndexSet.is_not_empty edges.succ_l.:(i) ||
             IndexSet.is_not_empty edges.succ_r.:(i) then
            push remaining i
        );
      (* Core loop:
         - pick a remaining candidate maximizing some heuristic
         - burn it
         - cleanup remaining candidates
         - try again *)
      (* Improve heuristic, avoid "crossing" candidates *)
      let eval i =
        IndexSet.cardinal edges.pred_l.:(i) *
        IndexSet.cardinal edges.succ_r.:(i) +
        IndexSet.cardinal edges.pred_r.:(i) *
        IndexSet.cardinal edges.succ_l.:(i)
      in
      let rec loop = function
        | [] -> ()
        | x :: xs as remaining ->
          let select (hx, _ as acc) y =
            let hy = eval y in
            if hy > hx then (hy, y) else acc
          in
          let _, x = List.fold_left select (eval x, x) xs in
          burn_bridge x;
          cleanup ();
          let remaining = List.filter (fun x -> eval x > 0) remaining in
          loop remaining
      in
      loop !remaining;
      burned
end

module Bridges = struct
  type 'b bridge = {
    id: int;
    mutable burned: bool;
    mutable succ_l: 'b IndexSet.t;
    mutable succ_r: 'b IndexSet.t;
    mutable pred_l: 'b IndexSet.t;
    mutable pred_r: 'b IndexSet.t;
  }

  let count = ref 0

  let new_bridge () = {
    id = (incr count; !count);
    burned = false;
    succ_l = IndexSet.empty;
    succ_r = IndexSet.empty;
    pred_l = IndexSet.empty;
    pred_r = IndexSet.empty;
  }

  let make_base (type n b) (c : n cardinal) : (n, (n, b) Sum.n bridge) vector =
    Vector.init c  (fun _ -> new_bridge ())

  let connect_l ia ba ib bb =
    ba.succ_l <- IndexSet.add ib ba.succ_l;
    bb.pred_l <- IndexSet.add ia bb.pred_l

  let connect_r ia ba ib bb =
    ba.succ_r <- IndexSet.add ib ba.succ_r;
    bb.pred_r <- IndexSet.add ia bb.pred_r

  let add_bridge (type n b)
      (base : (n, (n, b) Sum.n bridge) vector)
      (gen : (b, (n, b) Sum.n bridge) IndexBuffer.Gen.t)
      i0 i1
    =
    let open IndexBuffer in
    let b = new_bridge () in
    let i = Sum.inj_r (Vector.length base) (Gen.add gen b) in
    let b0 = base.:(i0) and b1 = base.:(i1) in
    let i0 = Sum.inj_l i0 and i1 = Sum.inj_l i1 in
    let l0 = IndexSet.is_not_empty b0.pred_l in
    let r0 = IndexSet.is_not_empty b0.pred_r in
    let l1 = IndexSet.is_not_empty b1.pred_l in
    let r1 = IndexSet.is_not_empty b1.pred_r in
    if l0 then (
      connect_l i0 b0 i b;
      connect_l i b i1 b1;
    );
    if r0 then (
      connect_r i0 b0 i b;
      connect_r i b i1 b1;
    );
    if l1 then (
      connect_l i1 b1 i b;
      connect_l i b i0 b0;
    );
    if r1 then (
      connect_r i1 b1 i b;
      connect_r i b i0 b0;
    );
    (i, b)

  let connect_l (type n b) (base : (n, (n, b) Sum.n bridge) vector) ia ib =
    connect_l (Sum.inj_l ia) base.:(ia) (Sum.inj_l ib) base.:(ib)

  let connect_r (type n b) (base : (n, (n, b) Sum.n bridge) vector) ia ib =
    connect_r (Sum.inj_l ia) base.:(ia) (Sum.inj_l ib) base.:(ib)

  let solve (type b) (burnable : b index -> bool) (bridges : (b, b bridge) vector) =
    let cleanable = ref [] in
    let eliminate i =
      let b = bridges.:(i) in
      begin
        if IndexSet.is_empty b.pred_l && IndexSet.is_empty b.succ_l then
          (* Merge R *)
          IndexSet.rev_iter begin fun i_0 ->
            let b_0 = bridges.:(i_0) in
            IndexSet.rev_iter begin fun i_1 ->
              let b_1 = bridges.:(i_1) in
              b_0.succ_r <- IndexSet.add i_1 b_0.succ_r;
              b_1.pred_r <- IndexSet.add i_0 b_1.pred_r;
            end b.succ_r
          end b.pred_r
        else if IndexSet.is_empty b.pred_r && IndexSet.is_empty b.succ_r then
          (* Merge L *)
          IndexSet.rev_iter begin fun i_0 ->
            let b_0 = bridges.:(i_0) in
            IndexSet.rev_iter begin fun i_1 ->
              let b_1 = bridges.:(i_1) in
              b_0.succ_l <- IndexSet.add i_1 b_0.succ_l;
              b_1.pred_l <- IndexSet.add i_0 b_1.pred_l;
            end b.succ_l
          end b.pred_l
        else if not (IndexSet.is_empty b.pred_l && IndexSet.is_empty b.pred_r) ||
                not (IndexSet.is_empty b.succ_l && IndexSet.is_empty b.succ_r) then
          (* Burn (Mixed LR) *)
          b.burned <- true
      end; (* Unregister *)
      begin
        IndexSet.iter begin fun pred ->
          let b' = bridges.:(pred) in
          b'.succ_l <- IndexSet.remove i b'.succ_l;
          if IndexSet.is_empty b'.succ_l && IndexSet.is_empty b'.succ_r then
            push cleanable pred;
        end b.pred_l;
        IndexSet.iter begin fun succ ->
          let b' = bridges.:(succ) in
          b'.pred_l <- IndexSet.remove i b'.pred_l;
          if IndexSet.is_empty b'.pred_l && IndexSet.is_empty b'.pred_r then
            push cleanable succ;
        end b.succ_l;
        IndexSet.iter begin fun pred ->
          let b' = bridges.:(pred) in
          b'.succ_r <- IndexSet.remove i b'.succ_r;
          if IndexSet.is_empty b'.succ_l && IndexSet.is_empty b'.succ_r then
            push cleanable pred;
        end b.pred_r;
        IndexSet.iter begin fun succ ->
          let b' = bridges.:(succ) in
          b'.pred_r <- IndexSet.remove i b'.pred_r;
          if IndexSet.is_empty b'.pred_l && IndexSet.is_empty b'.pred_r then
            push cleanable succ;
        end b.succ_r
      end;
      b.pred_l <- IndexSet.empty;
      b.succ_l <- IndexSet.empty;
      b.pred_r <- IndexSet.empty;
      b.succ_r <- IndexSet.empty;
    in
    Vector.iteri (fun i b ->
        if (IndexSet.is_empty b.succ_l && IndexSet.is_empty b.succ_r) ||
           (IndexSet.is_empty b.pred_l && IndexSet.is_empty b.pred_r) then
          eliminate i
      ) bridges;
    let rec cleanup () =
      match !cleanable with
      | [] -> ()
      | cleanable' ->
        cleanable := [];
        List.iter eliminate cleanable';
        cleanup ()
    in
    cleanup ();
    let eval i =
      let b = bridges.:(i) in
      IndexSet.cardinal b.pred_l * IndexSet.cardinal b.succ_r +
      IndexSet.cardinal b.pred_r * IndexSet.cardinal b.succ_l
    in
    let select (w, _ as candidate) i =
      let w' = eval i in
      if w' > w then
        (w', i)
      else
        candidate
    in
    let oc = open_out "bridges.dot" in
    let p fmt = Printf.kfprintf (fun oc -> output_char oc '\n') oc fmt in
    p "digraph G {";
    let edge label i j = p "  b%d -> b%d[label=%S];" (Index.to_int i) (Index.to_int j) label in
    Vector.iteri begin fun i b ->
      if burnable i then (
        IndexSet.iter (edge "L" i) b.succ_l;
        IndexSet.iter (edge "R" i) b.succ_r;
      )
    end bridges;
    p "}";
    let rec eliminate_remaining = function
      | [] -> ()
      | x :: xs ->
        let _, selected = List.fold_left select (eval x, x) xs in
        eliminate selected;
        cleanup ();
        let remaining = List.filter (fun x -> if eval x = 0 then (eliminate x; false) else true) (x :: xs) in
        eliminate_remaining remaining
    in
    let candidates =
      Vector.fold_lefti (fun acc i b ->
          cons_if (burnable i &&
                   not (IndexSet.is_empty b.pred_l && IndexSet.is_empty b.pred_r))
            i acc)
        [] bridges
    in
    eliminate_remaining candidates

end

(* How do we represent conflicts?

   If some state present a conflict, we start by building a map of preserved
   actions by lookahead symbol.
*)


module Conflict = struct

  type 'g actions = {
    shift: 'g item indexset;
    reduce: 'g item indexset;
  }

  let get_actions map t =
    match IndexMap.find_opt t map with
    | Some a -> a
    | None -> {shift = IndexSet.empty; reduce = IndexSet.empty}

  let add_shift g tr map =
    match Symbol.desc g (Transition.symbol g tr) with
    | N _ -> map
    | T term ->
      let items = Lr1.items g (Transition.target g tr) in
      IndexSet.iter (fun item -> assert (Item.position g item > 0)) items;
      let actions = get_actions map term in
      assert (IndexSet.is_empty actions.shift);
      IndexMap.add term {actions with shift = items} map

  let add_reduction g red map =
    let prod = Reduction.production g red in
    let item = Item.make g prod (Production.length g prod) in
    IndexSet.fold begin fun term map ->
      let actions = get_actions map term in
      let reduce = IndexSet.add item actions.reduce in
      IndexMap.add term {actions with reduce = reduce} map
    end (Reduction.lookaheads g red) map

  let remove_reduce g map (term, prod) =
    let actions = get_actions map term in
    let item = Item.make g prod (Production.length g prod) in
    let reduce = IndexSet.remove item actions.reduce in
    assert (reduce != actions.reduce);
    IndexMap.add term {actions with reduce} map

  type relation =
    | Shift_over_reduce
    | Reduce_over_shift
    | Reduce_reduce

  type 'g edge = {
    source: 'g item index;
    target: 'g item index;
    relation: relation;
  }

  let register_removed_shift g map register (term, state) =
    let actions = get_actions map term in
    assert (IndexSet.is_empty actions.shift);
    IndexSet.iter begin fun source ->
      IndexSet.iter begin fun target ->
        register {source; target; relation = Reduce_over_shift}
      end actions.reduce
    end (match Sum.prj (Lr1.cardinal g) state with
        | L lr1 -> Lr1.items g lr1
        | R lr0 -> Lr0.items g lr0)

  let register_removed_reduce g map register (term, prods) =
    let actions = get_actions map term in
    List.iter begin fun prod ->
      let source = Item.make g prod (Production.length g prod) in
      IndexSet.iter begin fun target ->
        register {source; target; relation = Shift_over_reduce}
      end actions.shift;
      IndexSet.iter begin fun target ->
        register {source; target; relation = Reduce_reduce}
      end actions.reduce
    end prods

  let process_lr1 g register lr1 =
    match
      Conflicts.silent_transition_conflicts g lr1,
      Conflicts.silent_reduction_conflicts g lr1
    with
    | [], [] -> ()
    | removed_shift, removed_reduce ->
      let actions =
        IndexMap.empty
        |> IndexSet.fold (add_shift g) (Transition.successors g lr1)
        |> IndexSet.fold (add_reduction g) (Reduction.from_lr1 g lr1)
      in
      (* Remove extra ones *)
      let actions =
        List.fold_left (remove_reduce g)
          actions (Conflicts.extra_reductions g lr1)
      in
      (* Register conflicts *)
      List.iter
        (register_removed_shift g actions register)
        removed_shift;
      List.iter
        (register_removed_reduce g actions register)
        removed_reduce

  type associativity =
    | Left
    | Right
    | Prec
    | Invalid
    | Neutral

  let solve (type g) (g : g grammar) =
    let items = Item.cardinal g in
    (* Collect all conflicts by item *)
    let successors = Vector.make items [] in
    let predecessors = Vector.make items [] in
    (* Lift representation to bridge base *)
    let module B = IndexBuffer.Gen.Make() in
    let base = Bridges.make_base items in
    (* Initialize arrays *)
    let register edge =
      successors.@(edge.source) <- List.cons edge;
      predecessors.@(edge.target) <- List.cons edge;
      match edge.relation with
      | Shift_over_reduce -> Bridges.connect_r base edge.source edge.target
      | Reduce_over_shift -> Bridges.connect_l base edge.source edge.target
      | Reduce_reduce ->
        Bridges.connect_l base edge.source edge.target;
        Bridges.connect_r base edge.source edge.target
    in
    Index.iter (Lr1.cardinal g) (process_lr1 g register);
    (* Represent merging candidates as bridges *)
    let bridges = B.get_generator () in
    let item_bridges = Vector.make items [] in
    let _ = Index.fold items None begin fun acc item ->
        if List.is_empty successors.:(item) &&
           List.is_empty predecessors.:(item) then
          (* Skip unused items *)
          acc
        else (
          begin match acc with
            | Some item'
              when (Index.equal (Item.production g item) (Item.production g item'))       ->
              (* Item from same production: new bridge! *)
              let _, b = Bridges.add_bridge base bridges item item' in
              item_bridges.@(item) <- List.cons (b, item');
              item_bridges.@(item') <- List.cons (b, item)
            | _ -> ()
          end;
          Some item
        )
      end
    in
    let bridges = IndexBuffer.Gen.freeze bridges in
    Bridges.solve
      (fun i -> match Sum.prj items i with L _ -> false | R _ -> true)
      (Vector.concat base bridges);
    let burned = ref 0 in
    Vector.iter (fun b -> if b.Bridges.burned then incr burned) bridges;
    Printf.eprintf "Bridges burned: %d/%d\n" !burned (Vector.length_as_int bridges);
    (* Generate SCC of the graph induced by conflicts *)
    let (module SCC) =
      Tarjan.indexed_scc items
        ~succ:(fun f i ->
            List.iter (fun edge -> f edge.target) successors.:(i);
            List.iter (fun (bridge,target) ->
                if not bridge.Bridges.burned then
                  f target
              ) item_bridges.:(i)
          )
    in
    (* Associativity is enforced in non-trivial components *)
    let oc = open_out_bin "conflicts.dot" in
    let p fmt = Printf.kfprintf (fun oc -> output_char oc '\n') oc fmt in
    p "digraph G {";
    let assocs =
      Vector.mapi begin fun scc nodes ->
        let self_sr = ref false in
        let self_rs = ref false in
        let self_rr = ref false in
        IndexSet.iter begin fun node ->
          List.iter begin fun edge ->
            let scc' = SCC.component.:(edge.source) in
            if Index.equal scc scc' then (
              match edge.relation with
              | Shift_over_reduce -> self_sr := true
              | Reduce_over_shift -> self_rs := true
              | Reduce_reduce     -> self_rr := true
            )
          end predecessors.:(node)
        end nodes;
        match !self_sr, !self_rs, !self_rr with
        | false, false, false -> Neutral
        | true , false, false -> Right
        | false, true , false -> Left
        | _ ->
          IndexSet.iter begin fun node ->
            p "  p%d[label=%S];" (Index.to_int node) (Item.to_string g node);
            List.iter begin fun edge ->
              let scc' = SCC.component.:(edge.source) in
              if Index.equal scc scc' then (
                p "  p%d -> p%d[label=%S];" (Index.to_int edge.source) (Index.to_int node)
                  (match edge.relation with
                   | Shift_over_reduce -> "R"
                   | Reduce_over_shift -> "L"
                   | Reduce_reduce -> "LR")
              )
            end predecessors.:(node);
            List.iter (fun (bridge,_target) ->
                if not bridge.Bridges.burned then (
                  p "  p%d -> b%d [dir=both];\n" (Index.to_int node) bridge.id;
                );
              ) item_bridges.:(node)
          end nodes;
          Invalid
          (*invalid_arg "cyclic precedences"*)
      end SCC.nodes;
    in
    p "}";
    close_out oc;
    let ranks = Vector.make SCC.n 0 in
    (* Refine associativity for other components *)
    Vector.iteri begin fun scc nodes ->
      let assoc = match assocs.:(scc) with
        | Neutral ->
          let left = ref 0 in
          let right = ref 0 in
          let visit edge node =
            let scc' = SCC.component.:(node) in
            if not (Index.equal scc scc') then
              match edge.relation, assocs.:(scc') with
              | Shift_over_reduce, (Neutral | Right) -> incr right
              | Reduce_over_shift, (Neutral | Left) -> incr left
              | _ -> ()
          in
          let visit_source edge = visit edge edge.source in
          let visit_target edge = visit edge edge.target in
          let visit_all arr f node = List.iter f arr.:(node) in
          IndexSet.iter (visit_all predecessors visit_source) nodes;
          IndexSet.iter (visit_all successors visit_target) nodes;
          if !left > !right
          then Left
          else Right
        | assoc -> assoc
      in
      assocs.:(scc) <- assoc;
      let rank = IndexSet.fold begin fun node rank ->
          List.fold_left begin fun rank edge ->
            let scc' = SCC.component.:(edge.source) in
            if Index.equal scc scc' then
              rank
            else
              let rank' = ranks.:(scc') in
              let rank' = match assocs.:(scc'), assoc with
                | Left, Left  | Right, Right -> rank'
                | Left, Right | Right, Left -> rank' + 1
                | _ -> assert false
              in
              Int.max rank rank'
          end rank predecessors.:(node)
        end nodes 0
      in
      ranks.:(scc) <- rank
    end SCC.nodes;
    (* Cleanup unused associativity *)
    Vector.iteri begin fun scc nodes ->
      let used =
        let rank = ranks.:(scc) in
        let visit node =
          ranks.:(SCC.component.:(node)) = rank
        in
        let visit_source edge = visit edge.source in
        let visit_target edge = visit edge.target in
        let visit_all arr f node = List.exists f arr.:(node) in
        (* Associativity is used if we have one successor or predecessor with
           the same rank *)
        IndexSet.exists (visit_all predecessors visit_source) nodes ||
        IndexSet.exists (visit_all successors visit_target) nodes
      in
      if not used then
        assocs.:(scc) <- Prec;
    end SCC.nodes;
    let it_ranks = Vector.make items (-1) in
    let it_assoc = Vector.make items Prec in
    Vector.iteri begin fun scc nodes ->
      let rank = ranks.:(scc) and assoc = assocs.:(scc) in
      IndexSet.iter begin fun node ->
        it_ranks.:(node) <- rank;
        it_assoc.:(node) <- assoc;
      end nodes
    end SCC.nodes;
    Index.iter (Production.cardinal g) begin fun prod ->
      let rank = ref (-1) in
      let assoc = ref Prec in
      for i = Production.length g prod - 1 downto 1 do
        let item = Item.make g prod i in
        if it_ranks.:(item) = -1 then (
          it_ranks.:(item) <- !rank;
          it_assoc.:(item) <- !assoc;
        ) else (
          rank := it_ranks.:(item);
          assoc := it_assoc.:(item);
        )
      done
    end;
    (it_ranks, it_assoc)
end

module Converter = struct
  let (!!) = Doc.text
  let (^^) = Doc.join

  let bind_rule lhs rhs =
    !!lhs ^^ !!": $ => " ^^ rhs ^^ !!",\n"

  let mangled g nt =
    Symbol.to_string ~mangled:true g (Symbol.inj_n g nt)

  let import_terminal g term =
    match Terminal.kind g term with
    | `EOF -> "token(\"EOF\")"
    | _ ->
      let rhs = Option.value (Terminal.alias g term)
          ~default:(Terminal.to_string g term)
      in
      if rhs = "" || rhs.[0] <> '"'
      then Printf.sprintf "token(%S)" rhs
      else Printf.sprintf "token(%s)" rhs

  let import_raw_producer g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N nt -> !!"$." ^^ !!(mangled g nt)

  let import_producer not_optional g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N n ->
      let doc = !!"$." ^^ !!(mangled g n) in
      if Nonterminal.nullable g n && not not_optional
      then Doc.wrap !!"optional(" !!")" doc
      else doc

  let symbol_nonnull ga sym =
    match Symbol.desc ga.g sym with
    | T t -> Terminal.kind ga.g t = `REGULAR
    | N n -> ga.nonnull_nt.?(n)

  let symbol_nullable g sym =
    match Symbol.desc g sym with
    | T _ -> false
    | N n -> Nonterminal.nullable g n

  let import_production ga ranks assocs prod =
    assert ga.nonnull_prod.?(prod);
    let rhs = (Production.rhs ga.g prod) in
    let not_optional = ref (Array.for_all (symbol_nullable ga.g) rhs) in
    let tail = ref [] in
    let last_rank = ref (-1, Conflict.Invalid) in
    let flush_tail () =
      match !tail with
      | [] -> !!"seq()"
      | [x] -> x
      | xs -> Doc.wrap !!"seq(" !!")" (Doc.concat !!"," Fun.id xs)
    in
    let flush_rank () =
      match !tail, !last_rank with
      | [], _ | _, (-1, _) -> ()
      | _ ->
        let level, assoc = !last_rank in
        let assoc = match assoc with
          | Left -> "prec.left"
          | Right -> "prec.right"
          | Invalid -> "prec.invalid"
          | Prec -> "prec"
          | Neutral -> "prec"
        in
        tail := [Doc.wrap !!(Printf.sprintf "%s(%d," assoc level) !!")" (flush_tail ())]
    in
    let add_sym rank sym =
      if symbol_nonnull ga sym then (
        if rank <> !last_rank then flush_rank ();
        tail := import_producer !not_optional ga.g sym :: !tail;
        not_optional := false
      );
      last_rank := rank
      (* Logic:
         - if sym is not non_null, skip
         - if (rank, assoc) <> last_rank, tail <> [] then flush_rank ()
         - last_rank := rank, assoc
         - if nullable && !optional
           then tail = option(sym) :: tail
           else tail = sym :: tail
         - optional := false
      *)
    in
    for pos = Array.length rhs - 1 downto 0 do
      let item = Item.make ga.g prod (pos + 1) in
      add_sym (ranks.:(item), assocs.:(item)) rhs.(pos)
    done;
    flush_rank ();
    flush_tail ()

  let import_nonterminals ga ranks assocs =
    (* Pre-compute productions defining a non-terminal *)
    let nt_prods = Vector.make (Nonterminal.cardinal ga.g) IndexSet.empty in
    let entrypoint = ref None in
    Index.rev_iter (Production.cardinal ga.g) begin fun prod ->
      if ga.valid_prod.?(prod) && ga.nonnull_prod.?(prod) then
        match Production.kind ga.g prod with
        | `REGULAR ->
          nt_prods.@(Production.lhs ga.g prod) <- IndexSet.add prod
        | `START ->
          if Option.is_none !entrypoint then
            let n = match Symbol.desc ga.g (Production.rhs ga.g prod).(0) with
              | Symbol.T _ -> assert false
              | Symbol.N n -> n
            in
            entrypoint := Some n
    end;
    let rules =
      (* Output all productions of a non-terminal *)
      Vector.to_seqi nt_prods |>
      Seq.filter_map begin fun (nt, prods) ->
        if IndexSet.is_empty prods then None else Some begin
            let rhs =
              if IndexSet.is_singleton prods then
                import_production ga ranks assocs (IndexSet.choose prods)

              else
                Doc.wrap !!"choice(\n" !!"\n)"
                  (Doc.indent 2 (Doc.concat !!",\n"
                                   (import_production ga ranks assocs)
                                   (IndexSet.elements prods)))
            in
            (nt, rhs)
          end
      end
    in
    (Option.get !entrypoint, rules)

  let convert_syntax ga ranks assocs basename =
    let entrypoint, rules = import_nonterminals ga ranks assocs in
    (*let entrypoint =
      if List.exists (fun (nt, _) -> mangled ga.g nt = "start") rules then
        "start"
      else
        List.find_map (fun (nt, _) ->
            if Nonterminal.kind ga.g nt = `START
            then Some (mangled ga.g nt)
            else None
          ) rules
        |> Option.get
      in*)
    Doc.list [
      !!"export default {\n";
      Doc.indent 2 @@ Doc.list [
        !!"name: '"; !!basename; !!"',\n";
        !!"rules: {\n";
        Doc.indent 2 @@ Doc.list [
          bind_rule "start" !!("$." ^ mangled ga.g entrypoint);
          Doc.list_map
            (fun (lhs, rhs) -> bind_rule (mangled ga.g lhs) rhs)
            (List.of_seq rules);
          (*Doc.list (List.filter_map import_token symbols);*)
        ];
        !!"}\n";
      ];
      !! "};\n";
    ]
end

let import g basename =
  let ga = analyze g in
  let ranks, assocs = Conflict.solve g in
  let doc = Converter.convert_syntax ga ranks assocs basename in
  Doc.render (output_substring stdout) 0 doc
