open Kernel.Info
open Fix.Indexing
open Utils
open Misc

let (.?()) = Boolvector.test

(* The logic:
   - Tree-sitter do not expect an explicit "EOF" symbol, we strip them from the
     original grammar
   - Rules involving `error` symbol are likely noise too, we ignore them
   - Tree-sitter do not support ϵ-rules -> rewrite grammar
   - Conflicts are specified with a slightly different formalism ->
     reverse-engineer conflict resolution from the generated automaton

   The flow:
   - analyze the grammar:
     - find which productions to import
     - find which derive non-null string (for rewriting of ϵ-rules and nts)
   - from the analysis, we can directly generate a tree-sitter template
   - but we don't stop here:
     - transform the conflicts in the automaton into a set of
       constraints
     - solve the constraints
     - inject the solution in the grammar prior to generation

   Constraints are solved as follow:
   - tree-sitter sets a precedence value at the level of productions
   - for each item, we will generate a variable representing its precedence level
   - the equations are all of the form `var ≥_{Left,Right,Prec} var`, so we can
     compute the SCC of the graph generated by these relations to rank them
   - however doing this naively introduce too many precedence levels and do not
     support associativity out of the box
   - if all rules involved in a cycle are ... TODO
*)

(* Pre-compute some properties of the grammar *)
type 'g analysis = {
  g: 'g grammar;
  (* Productions to consider *)
  valid_prod: 'g production Boolvector.t;
  (* Non-terminals deriving a non-empty string *)
  nonnull_nt: 'g nonterminal Boolvector.t;
  (* Productions deriving a non-empty string *)
  nonnull_prod: 'g production Boolvector.t;
}

let analyze g =
  (* A production is valid if it has no `error` symbol *)
  let valid_prod = Boolvector.init (Production.cardinal g) begin fun prod ->
      Array.for_all (fun sym ->
          match Symbol.desc g sym with
          | T t -> Terminal.kind g t <> `ERROR
          | _ -> true
        ) (Production.rhs g prod)
    end
  in
  (* Pre-compute productions in which a non-terminal occurs *)
  let nt_occurrences = Vector.make (Nonterminal.cardinal g) IndexSet.empty in
  Index.rev_iter (Production.cardinal g) begin fun prod ->
    if valid_prod.?(prod) then
      Array.iter begin fun sym ->
        match Symbol.desc g sym with
        | T _ -> ()
        | N nt -> nt_occurrences.@(nt) <- IndexSet.add prod
      end (Production.rhs g prod)
  end;
  (* Determine nt and prod that can derive a non-empty string *)
  let nonnull_nt = Boolvector.make (Nonterminal.cardinal g) false in
  let nonnull_prod = Boolvector.make (Production.cardinal g) false in
  let rec set_prod prod =
    if not nonnull_prod.?(prod) then (
      Boolvector.set nonnull_prod prod;
      set_nt (Production.lhs g prod)
    )
  and set_nt nt =
    if not nonnull_nt.?(nt) then (
      Boolvector.set nonnull_nt nt;
      IndexSet.iter set_prod nt_occurrences.:(nt)
    )
  in
  Index.iter (Production.cardinal g) begin fun prod ->
    if
      Array.exists (fun sym ->
        match Symbol.desc g sym with
        | N _ -> false
        | T t -> match Terminal.kind g t with
          | `REGULAR -> true
          | `EOF -> false
          | `ERROR | `PSEUDO -> false
      ) (Production.rhs g prod)
    then set_prod prod
  end;
  {g; valid_prod; nonnull_nt; nonnull_prod}

(* Documents for constructing indented output *)
module Doc = struct
  type document =
    | Text of string
    | Indent of (int * document)
    | Join of document * document

  let empty = Text ""

  let text x = Text x

  let join x y =
    match x, y with
    | Text "", v | v, Text "" -> v
    | _ -> Join (x, y)

  let list = function
    | [] -> empty
    | [x] -> x
    | x :: xs -> List.fold_left join x xs

  let list_map f docs = list (List.map f docs)

  let indent n = function
    | Text "" -> Text ""
    | Indent (m, doc) -> Indent (n + m, doc)
    | doc -> Indent (n, doc)

  let wrap a b c = join a (join c b)

  let rec concat sep f ?(first=f) = function
    | [] -> empty
    | [x] -> first x
    | x :: xs -> join (first x) (join sep (concat sep f xs))

  let padding = String.make 80 ' '

  let rec render_text nl o n pos text =
    match String.index_from_opt text pos '\n' with
    | None ->
      let len = String.length text - pos in
      if len > 0 then (
        if !nl then (
          o padding 0 (Int.min 80 n);
          nl := false;
        );
        o text pos len
      );
    | Some pos' ->
      if pos' > pos && !nl then (
        o padding 0 (Int.min 80 n);
        nl := false;
      );
      let pos' = pos' + 1 in
      o text pos (pos' - pos);
      nl := true;
      render_text nl o n pos' text

  let rec render nl o n = function
    | Text text -> render_text nl o n 0 text
    | Indent (d, doc) -> render nl o (n + d) doc
    | Join (a, b) ->
      render nl o n a;
      render nl o n b

  let render o n doc = render (ref false) o n doc
end

module Converter = struct
  let (!!) = Doc.text
  let (^^) = Doc.join

  let bind_rule lhs rhs =
    !!lhs ^^ !!": $ => " ^^ rhs ^^ !!",\n"

  let mangled g nt =
    Symbol.to_string ~mangled:true g (Symbol.inj_n g nt)

  let import_terminal g term =
    match Terminal.kind g term with
    | `EOF -> "token(\"EOF\")"
    | _ ->
      let rhs = Option.value (Terminal.alias g term)
          ~default:(Terminal.to_string g term)
      in
      if rhs = "" || rhs.[0] <> '"'
      then Printf.sprintf "token(%S)" rhs
      else Printf.sprintf "token(%s)" rhs

  let import_raw_producer g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N nt -> !!"$." ^^ !!(mangled g nt)

  let import_producer g prod =
    match Symbol.desc g prod with
    | T t -> !!(import_terminal g t)
    | N n ->
      let doc = !!"$." ^^ !!(mangled g n) in
      if Nonterminal.nullable g n
      then Doc.wrap !!"optional(" !!")" doc
      else doc

  let symbol_nonnull ga sym =
    match Symbol.desc ga.g sym with
    | T t -> Terminal.kind ga.g t = `REGULAR
    | N n -> ga.nonnull_nt.?(n)

  let symbol_nullable g sym =
    match Symbol.desc g sym with
    | T _ -> false
    | N n -> Nonterminal.nullable g n

  let import_producers ga syms tail =
    match List.filter (symbol_nonnull ga) syms, tail with
    | [], Some tail -> tail
    | [], _ -> assert false
    | [x], None -> import_raw_producer ga.g x
    | xs, _ ->
      let first =
        if List.for_all (symbol_nullable ga.g) xs
        then import_raw_producer ga.g
        else import_producer ga.g
      in
      let rhs = Doc.concat !!"," ~first (import_producer ga.g) xs in
      let rhs = match tail with
        | None -> rhs
        | Some tail -> rhs ^^ !!"," ^^ tail
      in
      Doc.wrap !!"seq(" !!")" rhs

  let import_rank (kind, level) doc =
    let lhs =
      Printf.sprintf "%s(%d,"
        (match kind with
         | `Neutral -> "prec"
         | `Left    -> "prec.left"
         | `Right   -> "prec.right"
         | `Invalid -> "prec")
        (level + 1)
    in
    Doc.wrap !!lhs !!")" doc

  let import_production ga prod =
    assert ga.nonnull_prod.?(prod);
    let rhs = Production.rhs ga.g prod in
    import_producers ga (Array.to_list rhs) None

    (*let index = Production.to_int br.production in
    let vars =
      let get_rank (p,v) =
        (p, Conflicts.solution.scc_rank.(Conflicts.solution.scc_of.(v)))
      in
      Conflicts.vars.(index)
      |> List.sort (fun (p0,_) (p1,_) -> Int.compare p0 p1)
      |> List.map get_rank
    in
    let rec merge_ranks = function
      | (p1,r1) :: (p2,r2) :: rest when r1 = r2 ->
        merge_ranks ((p1,r1) :: rest)
      | [] -> []
      | r :: rs -> r :: merge_ranks rs
    in
    let rec shift_ranks = function
      | [] -> None
      | (p,r) :: rest ->
        match shift_ranks rest with
        | None -> Some (r, [])
        | Some (r', rest) -> Some (r, (p,r') :: rest)
    in
    let pos = ref (Array.length br.rhs) in
    let extract pos' =
      let result = ref [] in
      while !pos > pos' do
        decr pos;
        result := br.rhs.(!pos) :: !result
      done;
      !result
      in*)
    (*match shift_ranks (merge_ranks vars) with
    | None -> import_producers (extract 0) None
    | Some (rank, ranks) ->
      let tail = List.fold_right (fun (p, r) tail ->
          Some (import_rank r (import_producers (extract p) tail))
        ) ranks None
      in
      import_rank rank (import_producers (extract 0) tail)*)


  let import_nonterminals ga =
    (* Pre-compute productions defining a non-terminal *)
    let nt_prods = Vector.make (Nonterminal.cardinal ga.g) IndexSet.empty in
    let entrypoint = ref None in
    Index.rev_iter (Production.cardinal ga.g) begin fun prod ->
      if ga.valid_prod.?(prod) && ga.nonnull_prod.?(prod) then
        match Production.kind ga.g prod with
        | `REGULAR ->
          nt_prods.@(Production.lhs ga.g prod) <- IndexSet.add prod
        | `START ->
          if Option.is_none !entrypoint then
            let n = match Symbol.desc ga.g (Production.rhs ga.g prod).(0) with
              | Symbol.T _ -> assert false
              | Symbol.N n -> n
            in
            entrypoint := Some n
    end;
    let rules =
      (* Output all productions of a non-terminal *)
      Vector.to_seqi nt_prods |>
      Seq.filter_map begin fun (nt, prods) ->
        if IndexSet.is_empty prods then None else Some begin
            let rhs =
              if IndexSet.is_singleton prods then
                import_production ga (IndexSet.choose prods)
              else
                Doc.wrap !!"choice(\n" !!"\n)"
                  (Doc.indent 2 (Doc.concat !!",\n"
                                   (import_production ga) (IndexSet.elements prods)))
            in
            (nt, rhs)
          end
      end
    in
    (Option.get !entrypoint, rules)

  let convert_syntax ga basename =
    let entrypoint, rules = import_nonterminals ga in
    (*let entrypoint =
      if List.exists (fun (nt, _) -> mangled ga.g nt = "start") rules then
        "start"
      else
        List.find_map (fun (nt, _) ->
            if Nonterminal.kind ga.g nt = `START
            then Some (mangled ga.g nt)
            else None
          ) rules
        |> Option.get
      in*)
    Doc.list [
      !!"export default {\n";
      Doc.indent 2 @@ Doc.list [
        !!"name: '"; !!basename; !!"',\n";
        !!"rules: {\n";
        Doc.indent 2 @@ Doc.list [
          bind_rule "start" !!("$." ^ mangled ga.g entrypoint);
          Doc.list_map
            (fun (lhs, rhs) -> bind_rule (mangled ga.g lhs) rhs)
            (List.of_seq rules);
          (*Doc.list (List.filter_map import_token symbols);*)
        ];
        !!"}\n";
      ];
      !! "};\n";
    ]
end

let import g basename =
  let ga = analyze g in
  let doc = Converter.convert_syntax ga basename in
  Doc.render (output_substring stdout) 0 doc
